# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  TWILIO_SID: 'AC683f318a5ea055f1af95caa3c0d21519'
  TWILIO_TOKEN: '73a80106803aae0940a1ca9a12fce5d6'
  TWILIO_NUMBER: '+33756796481'
  UBER_SERVER_TOKEN: "cSTsnO8I-FppZy6gPThunm55JanGjCE9KMZlbizK"
  UBER_CLIENT_ID: "JJF7pt-3FvSt2xeDCiBJfszIS7wNwnPk"
  UBER_CLIENT_SECRET: "5CRwa-mLLkg9xP4Lt67ipUxeReS8D7cswV5S1wDA"
  RECAST_TOKEN: 'ffe39be65f8d44796f040267385a642e'

production:
  TWILIO_SID: 'AC683f318a5ea055f1af95caa3c0d21519'
  TWILIO_TOKEN: '73a80106803aae0940a1ca9a12fce5d6'
  TWILIO_NUMBER: '+33756796481'
  UBER_SERVER_TOKEN: "cSTsnO8I-FppZy6gPThunm55JanGjCE9KMZlbizK"
  UBER_CLIENT_ID: "JJF7pt-3FvSt2xeDCiBJfszIS7wNwnPk"
  UBER_CLIENT_SECRET: "5CRwa-mLLkg9xP4Lt67ipUxeReS8D7cswV5S1wDA"
  RECAST_TOKEN: 'ffe39be65f8d44796f040267385a642e'
