development:
  TWILIO_SID: 'AC683f318a5ea055f1af95caa3c0d21519'
  TWILIO_TOKEN: '73a80106803aae0940a1ca9a12fce5d6'
  TWILIO_NUMBER: '+33756796481'
  UBER_SERVER_TOKEN: 'csX7Pq6MeShJGUJUCBZxnt_cBL7IchtesDQ9c40G'
  UBER_CLIENT_ID: 'JJF7pt-3FvSt2xeDCiBJfszIS7wNwnPk'
  UBER_CLIENT_SECRET: 'Bs4rAofmK4GA8T39kY56q-C4UM5vFClNN_mYH98F'
  RECAST_TOKEN: 'ffe39be65f8d44796f040267385a642e'
